### ISSUE TITLE
[BUG] Error in VAE decoding chunk 0: expected np.ndarray (got list)

### ISSUE THREAD

**Issue by Keylin2935** [gregcmartin/HunyuanVideo_MLX#13]
**System Information**
- macOS Version: 15.2
- Mac Model (M1/M2/M3): M4 Max
- RAM: 64
- MLX Version: 0.21.1
- Python Version: 3.11.11

**Describe the Bug**
After fresh repo cloning, on python vent, I launch 1 (or more) frame(s) generation with sample_video_mps.py command, and after about 5 minutes, I do not have any video (or images) generated, I do have the following errors:

024-12-21 22:19:54.254 | ERROR    | hyvideo.diffusion.pipelines.pipeline_hunyuan_video:__call__:806 - Error in VAE decoding chunk 0: expected np.ndarray (got list)
Error in VAE decoding: expected np.ndarray (got list)
Error in post-processing: expected np.ndarray (got list)
Error in generation: expected np.ndarray (got list)
2024-12-21 22:19:54.290 | ERROR    | hyvideo.inference:predict:411 - Generation failed: expected np.ndarray (got list)
2024-12-21 22:19:54.290 | ERROR    | __main__:main:199 - Error occurred: expected np.ndarray (got list)

**To Reproduce**

1. Run command :
python sample_video_mps.py 

2. With parameters:
--video-size 544 960 \          
    --prompt "A cat walks on the grass, realistic style." \
    --video-length 1 \
    --precision fp16 \
    --vae-precision fp16 \
    --text-encoder-precision fp16 \
    --text-encoder-precision-2 fp16

3. See error:
2024-12-21 22:14:53.888 | INFO     | hyvideo.diffusion.pipelines.pipeline_hunyuan_video:__call__:767 - Final shape: (1, 16, 1, 68, 120)
2024-12-21 22:14:53.888 | INFO     | hyvideo.diffusion.pipelines.pipeline_hunyuan_video:__call__:768 - Target latents shape: (1, 16, 1, 68, 120)
2024-12-21 22:19:54.254 | ERROR    | hyvideo.diffusion.pipelines.pipeline_hunyuan_video:__call__:806 - Error in VAE decoding chunk 0: expected np.ndarray (got list)
Error in VAE decoding: expected np.ndarray (got list)
Error in post-processing: expected np.ndarray (got list)
Error in generation: expected np.ndarray (got list)
2024-12-21 22:19:54.290 | ERROR    | hyvideo.inference:predict:411 - Generation failed: expected np.ndarray (got list)
2024-12-21 22:19:54.290 | ERROR    | __main__:main:199 - Error occurred: expected np.ndarray (got list)
Traceback (most recent call last):
  File "/Users/keylin/hunyuanvideo/HunyuanVideo_MLX/sample_video_mps.py", line 203, in <module>
    main()
  File "/Users/keylin/hunyuanvideo/HunyuanVideo_MLX/sample_video_mps.py", line 200, in main
    raise e
  File "/Users/keylin/hunyuanvideo/HunyuanVideo_MLX/sample_video_mps.py", line 176, in main
    outputs = pipeline.predict(
              ^^^^^^^^^^^^^^^^^
  File "/Users/keylin/hunyuanvideo/HunyuanVideo_MLX/hyvideo/inference.py", line 382, in predict
    samples = self.pipeline(
              ^^^^^^^^^^^^^^
  File "/Users/keylin/hunyuanvideo/HunyuanVideo_MLX/hyvideo/diffusion/pipelines/pipeline_hunyuan_video.py", line 842, in __call__
    raise e
  File "/Users/keylin/hunyuanvideo/HunyuanVideo_MLX/hyvideo/diffusion/pipelines/pipeline_hunyuan_video.py", line 825, in __call__
    raise e
  File "/Users/keylin/hunyuanvideo/HunyuanVideo_MLX/hyvideo/diffusion/pipelines/pipeline_hunyuan_video.py", line 819, in __call__
    raise e
  File "/Users/keylin/hunyuanvideo/HunyuanVideo_MLX/hyvideo/diffusion/pipelines/pipeline_hunyuan_video.py", line 798, in __call__
    chunk_decoded = self.vae.decode(chunk)["sample"]
                    ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/keylin/hunyuanvideo/HunyuanVideo_MLX/hyvideo/vae/mlx_vae.py", line 74, in decode
    z = torch.from_numpy(z.astype(mx.float32).tolist())
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: expected np.ndarray (got list)

**Expected Behavior**
An image (for 1 frame generation) or a video should be generated thanks to the command sample_video_mps.py

**Screenshots/Videos**
If applicable, add screenshots or videos to help explain your problem.

**Additional Context**
- Video resolution used: 544 960 \          
- Number of frames: 1
- Prompt used:   "A cat walks on the grass, realistic style.
- Any environment variables set:
# MLX/Metal Optimization Settings
export PYTORCH_MPS_HIGH_WATERMARK_RATIO=0.0
export PYTORCH_MPS_LOW_WATERMARK_RATIO=0.0
export PYTORCH_MPS_ALLOCATOR_POLICY=garbage_collection
export MPS_USE_GUARD_MODE=1
export MPS_ENABLE_MEMORY_GUARD=1
export PYTORCH_MPS_SYNC_OPERATIONS=1
export PYTORCH_MPS_AGGRESSIVE_MEMORY_CLEANUP=1

**Comment by scalar27** [comment]
Same problem for me.  I was just about to post the same bug report!

**Comment by pickettd** [comment]
I tried fixing up a few of these little errors this morning using 3.5 Sonnet. I was able to get the pipeline to complete without error when running in float32 (or float16 if I modified more lines in the code) and save an output file - but the output doesn't look like a image or video (just black screen or garbled pixels). You can see the branch I pushed with the small tweaks here: https://github.com/pickettd/HunyuanVideo_MLX/tree/output-without-error

For example to fix this particularly issue, Sonnet suggested changing line 74 of hyvideo/vae/mlx_vae.py to be
`z = torch.from_numpy(np.array(z.astype(mx.float32)))`

**Comment by andi-808** [comment]
Can confirm I also get a black video. It seems other people are experiencing the same on another repo. I wonder who has actually got this working.

**Comment by edwios** [comment]
> Can confirm I also get a black video. It seems other people are experiencing the same on another repo. I wonder who has actually got this working.

Did you not run into other errors as well? I have to fix quite a few different python files in order to get it to generate and save a black video successfully. Also, for this particularly issue, I also have to convert x and z to float16 otherwise it will failed due to different dtypes between bias and weights.

**Comment by andi-808** [comment]
Yes I had to do these conversions as well. The channel ordering at the end seemed to be wrong as well, the bit where it’s actually saving the video.

**Comment by edwios** [comment]
> Yes I had to do these conversions as well. The channel ordering at the end seemed to be wrong as well, the bit where it’s actually saving the video.

Then I wonder how @gregcmartin got it to work in the first place... at the least, `mlx_vae.py` never worked from the beginning when the initial commit has `x = torch.from_numpy(x.tolist())` which would die with the TypeError: expected np.ndarray (got list). Later fixes including the latest one give similar exceptions. Without this `MLXVAE` class working, no video could be produced at all. Not to mention `HunyuanVideoPipeline.Output` also wouldn't work since Output is not a member of HunyuanVideoPipeline.

**Comment by andi-808** [comment]
Yes everything you mentioned there I needed to fix. The main repo has a new fp8 quantised model which might be useful for memory utilisation, perhaps converting each layer that is in use to fp16 for the operation and then back to fp8 for memory storage might help? It seems going from fp32 to fp16 has been a problem for many people with these video models… fp8 to fp16 may improve the situation? Who knows.

**Comment by edwios** [comment]
> Yes everything you mentioned there I needed to fix. The main repo has a new fp8 quantised model which might be useful for memory utilisation, perhaps converting each layer that is in use to fp16 for the operation and then back to fp8 for memory storage might help? It seems going from fp32 to fp16 has been a problem for many people with these video models… fp8 to fp16 may improve the situation? Who knows.

I don't think it is the type casting issue. I've spent some time looking into the latent values, they have become bigger and bigger during the denoising process, and by the time it finished, many of them have values that are way above float16, that's why you got black pictures since when casted to float16, they have come +/-inf and finally nan.

I don't think the denoising process is implemented correctly and then, there is this in the beginning to zero out the initial latents (which is supposed to be random noise) 🤔:

```
    # Scale latents
    latents = latents * timesteps[0]
    # 4. Denoising loop with MLX operations
```

**Comment by andi-808** [comment]
I suppose we’d have to look back at the original repo to see what was meant to happen during this stage and re-implement it so it works with fp16 or even with the new fp8 model they released

**Comment by Keylin2935** [comment]
Hello,
I find a working workflow made and tested by a Japanese guy:
https://zenn.dev/robustonian/articles/hunyuanvideo_mac
It seems that only the Q8_0 gguf quantization is working for the moment.
It is very slow for the moment, more than 1 hour for a 3 seconds video, but I guess when the HunyuanVideo workflow will be optimized for MAC, it could be far better.

In short way:
We need Comfyui (for sure)
and then the following files:
- clip_l.safetensors
https://huggingface.co/comfyanonymous/flux_text_encoders/blob/main/clip_l.safetensors ->models/clip
- llava_llama3_fp16.safetensors
https://huggingface.co/Comfy-Org/HunyuanVideo_repackaged/blob/main/split_files/text_encoders/llava_llama3_fp16.safetensors ->models/text_encoders
- hunyuan-video-t2v-720p-Q8_0.gguf
https://huggingface.co/city96/HunyuanVideo-gguf/tree/main ->models/unet
- hunyuan_video_vae_bf16.safetensors
https://huggingface.co/Kijai/HunyuanVideo_comfy/blob/main/hunyuan_video_vae_bf16.safetensors ->models/vae

The correct workflow:
https://comfyanonymous.github.io/ComfyUI_examples/hunyuan_video/hunyuan_video_text_to_video.json

On my Macbook pro M4 Max with 64Gb of Ram, I succeed to generate:
- a video of 73 frames in 848 x 480 with 20 steps in about 1h10. (the video is ok)

I am currently trying to generate a video in 1280x720 of 121 frames with 8 steps to test, it is in going, I will keep you update.

**Comment by andi-808** [comment]
Cool! I have it working now. Thanks for this.

**Comment by Keylin2935** [comment]
@andi-808, you are welcome :) .
To add more info, 1 step generation (1/121) in 1280x720, for me, take about 2h30. So for 8 steps, it would be 20h, and thus for 20 steps => 50h.... Several tests show me that that the most impactful criterion is the number of images to generate. indeed, 1 frame in 1280x720 with 25 steps only takes about 5 minutes. I will try to do more tests later to give more metrics.

**Comment by andi-808** [comment]
Yes it is very slow for the duration of video. I’d be quite interested in changing it to image to video.
