### ISSUE TITLE
[BUG] Seriously, has anyone got this to work at all !?

### ISSUE THREAD

**Issue by edwios** [gregcmartin/HunyuanVideo_MLX#15]
**System Information**
- macOS Version: 15.2
- Mac Model (M1/M2/M3): M1
- RAM: 64GB
- MLX Version: 0.21.1
- Python Version: 3.11.7

**Describe the Bug**

The [exception in mlx_vae.py](https://github.com/gregcmartin/HunyuanVideo_MLX/issues/12) alone would stopped any video from being produced (and no, `float32`won't work because vae was loaded as `float16`), let alone other obvious mistakes in the codes such as 

```
return array.astype(mx.float32).numpy()
```

in `pipeline_hunyuan_video.py` -- mx.core.array has no attribute numpy, and 

```
return HunyuanVideoPipeline.Output(...)
```

in `inference.py` which `Output` in `HunyuanVideoPipeline` is not an attribute but an alias to `HunyuanVideoPipelineOutput`.

Also the error when array of torch tensors `[frame for frame in video]` are passed to `imageio.mimsave()` where numpy array is expected, and that `video` is (C, T, H, W) which would yield `frame` of (T, H, W) instead of the expected (H, W, C) order. 

I just couldn't understand how on earth could someone be able to produce a video without running into any one of these fatal exceptions. 

Lastly, I've got all these fixed (at least no longer getting any exceptions from any of the above), yet only videos with black picture were generated. The last few logs I've got were:

```
2024-12-26 22:25:00.029 | INFO     | hyvideo.diffusion.pipelines.pipeline_hunyuan_video:__call__:735 - Before reshape - noise_pred: (1, 2040, 3072), latents: (1, 16, 1, 68, 120)
2024-12-26 22:25:00.029 | INFO     | hyvideo.diffusion.pipelines.pipeline_hunyuan_video:__call__:741 - Initial noise_pred shape: (1, 2040, 3072)
2024-12-26 22:25:00.029 | INFO     | hyvideo.diffusion.pipelines.pipeline_hunyuan_video:__call__:743 - After flatten shape: (2040, 3072)
2024-12-26 22:25:00.029 | INFO     | hyvideo.diffusion.pipelines.pipeline_hunyuan_video:__call__:745 - After projection shape: (2040, 16)
2024-12-26 22:25:00.029 | WARNING  | hyvideo.diffusion.pipelines.pipeline_hunyuan_video:__call__:753 - Spatial dimensions mismatch: got 2040, expected 8160
2024-12-26 22:25:00.029 | INFO     | hyvideo.diffusion.pipelines.pipeline_hunyuan_video:__call__:763 - After spatial adjustment: (1, 8160, 16)
2024-12-26 22:25:00.029 | INFO     | hyvideo.diffusion.pipelines.pipeline_hunyuan_video:__call__:765 - After transpose: (1, 16, 8160)
2024-12-26 22:25:00.029 | INFO     | hyvideo.diffusion.pipelines.pipeline_hunyuan_video:__call__:767 - Final shape: (1, 16, 1, 68, 120)
2024-12-26 22:25:00.029 | INFO     | hyvideo.diffusion.pipelines.pipeline_hunyuan_video:__call__:768 - Target latents shape: (1, 16, 1, 68, 120)
2024-12-26 22:29:49.082 | INFO     | hyvideo.inference:predict:401 - Generation successful, time: 326.09s
2024-12-26 22:29:49.083 | INFO     | __main__:main:189 - Saving video...
Shape and types of videos: torch.Size([1, 3, 1, 544, 960]), torch.float32, <class 'torch.Tensor'>
Shape and types of video: torch.Size([3, 1, 544, 960]), torch.float32, <class 'torch.Tensor'>
Shape and types of permuted video: torch.Size([1, 544, 960, 3]), torch.float32, <class 'torch.Tensor'>
Shape and types of frame: torch.Size([544, 960, 3]), torch.float32, <class 'torch.Tensor'>
2024-12-26 22:29:52.128 | INFO     | __main__:main:214 - Video saved to results/42.mp4
```

**To Reproduce**

Follow installation procedure provided in this repo, then 

```
python sample_video_mps.py \
    --prompt "a cat is running, realistic." \
    --video-size 540 960 \
    --video-length 1 \
    --precision fp16 \
    --vae-precision fp16 \
    --text-encoder-precision fp16 \
    --text-encoder-precision-2 fp16 \
    --enable-quantization \
    --quantization-bits 4 \
    --exclude-from-quantization vae embedders \
    --num-inference-steps 10
```

I have also tried:

```
python sample_video_mps.py --prompt "a cat is running, realistic." --video-size 540 960  --num-inference-steps 10 --video-length 1
```

and still got the same result.

**Error Message/Logs**
Various. See above.

**Expected Behavior**
A video frame that is not black is produced.

**Screenshots/Videos**
If applicable, add screenshots or videos to help explain your problem.

**Additional Context**
- Video resolution used: 384x256, 960x540
- Number of frames: 1, 5
- Prompt used: a cat is running, realistic.
- Any environment variables set: Default

**Comment by neorrk** [comment]
I don't think so.

**Comment by vashat** [comment]
I am having exactly the same problems on a M3 Max 48 GB Sequoia 15.1.1.
I also had to fix problems in the code, for example I run into this:

```python sample_video_mps.py --prompt "Rocket liftoff" --video-size 544 960 --video-length 1 --precision fp16 --vae-precision fp16 --text-encoder-precision fp16 --text-encoder-precision-2 fp16```


```
2024-12-30 22:10:22.497 | ERROR    | __main__:main:199 - Error occurred: expected np.ndarray (got list)
Traceback (most recent call last):
  File "/Users/admin/scripts/HunyuanVideo_MLX/sample_video_mps.py", line 203, in <module>
    main()
  File "/Users/admin/scripts/HunyuanVideo_MLX/sample_video_mps.py", line 200, in main
    raise e
  File "/Users/admin/scripts/HunyuanVideo_MLX/sample_video_mps.py", line 176, in main
    outputs = pipeline.predict(
              ^^^^^^^^^^^^^^^^^
  File "/Users/admin/scripts/HunyuanVideo_MLX/hyvideo/inference.py", line 382, in predict
    samples = self.pipeline(
              ^^^^^^^^^^^^^^
  File "/Users/admin/scripts/HunyuanVideo_MLX/hyvideo/diffusion/pipelines/pipeline_hunyuan_video.py", line 842, in __call__
    raise e
  File "/Users/admin/scripts/HunyuanVideo_MLX/hyvideo/diffusion/pipelines/pipeline_hunyuan_video.py", line 825, in __call__
    raise e
  File "/Users/admin/scripts/HunyuanVideo_MLX/hyvideo/diffusion/pipelines/pipeline_hunyuan_video.py", line 819, in __call__
    raise e
  File "/Users/admin/scripts/HunyuanVideo_MLX/hyvideo/diffusion/pipelines/pipeline_hunyuan_video.py", line 798, in __call__
    chunk_decoded = self.vae.decode(chunk)["sample"]
                    ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/admin/scripts/HunyuanVideo_MLX/hyvideo/vae/mlx_vae.py", line 74, in decode
    z = torch.from_numpy(z.astype(mx.float32).tolist())
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: expected np.ndarray (got list)
```

There were several of these problems I had to fix but in the end I got stuck in the video export as @edwios mentioned (since imageio.mimsave() receives wrong video format). The code could not possibly work for anybody as it is now with so many issues?

**Comment by surjikal** [comment]
I managed to get this:
![output](https://github.com/user-attachments/assets/2e09515d-9f7a-494c-8705-03f403128bb2)

This was done with pretty much the same fixes you guys have been talking about already, and making sure to use fp32. Without fp32, a bunch of NaNs show up in the data after `z = self.post_quant_conv(z)` in `hyvideo/vae/autoencoder_kl_causal_3d.py`
