### ISSUE TITLE
RuntimeError: Input type (float) and bias type (c10::Half) should be the same

### ISSUE THREAD

**Issue by Keylin2935** [gregcmartin/HunyuanVideo_MLX#5]
Hardware: M4 max 64GB, MacOS 15.2
Context: After cloning the repo, on python venv and after following all installation steps.
and the venv content:
(venv) (base) keylin@MacBook-Pro-Keylin HunyuanVideo_MLX % cat .env

HF_TOKEN=hf_xxxxxxxxxxxxxxxxxxxxxxxx # hidden key for display
PYTORCH_MPS_HIGH_WATERMARK_RATIO=0.3
PYTORCH_MPS_LOW_WATERMARK_RATIO=0.2
PYTORCH_MPS_ALLOCATOR_POLICY=garbage_collection
MPS_USE_GUARD_MODE=1
MPS_ENABLE_MEMORY_GUARD=1
PYTORCH_MPS_SYNC_OPERATIONS=1

Description: When I execute the following command:
python sample_video_mps.py \
    --mmgp-mode \
    --mmgp-config configs/mmgp_mlx.json \
    --video-size 544 960 \
    --prompt "A cat walks on the grass, realistic style." \
    --video-length 1 \
    --precision fp16 \
    --vae-precision fp16 \
    --text-encoder-precision fp16 \
    --text-encoder-precision-2 fp16

I do have the following errors:
2024-12-18 22:08:54.481 | ERROR    | hyvideo.inference:predict:391 - Generation failed: Input type (float) and bias type (c10::Half) should be the same
2024-12-18 22:08:54.481 | ERROR    | __main__:main:218 - Error occurred: Input type (float) and bias type (c10::Half) should be the same

To be more precise please find below the related stack:

2024-12-18 22:08:45.768 | DEBUG    | hyvideo.inference:predict:344 - 
            height: 544
            width: 960
            video_length: 1
            prompt: ['A cat walks on the grass, realistic style.']
            negative_prompt: ['Aerial view, aerial view, overexposed, low quality, deformation, a poor composition, bad hands, bad teeth, bad eyes, bad limbs, distortion']
            seed: None
            steps: 25
            videos_per_prompt: 1
            guidance_scale: 7.0
            n_tokens: 2040
            flow_shift: 7.0
            embedded_guidance_scale: 6.0
        
  0%|                                                                            | 0/25 [00:00<?, ?it/s]/opt/anaconda3/lib/python3.12/site-packages/torch/amp/autocast_mode.py:266: UserWarning: User provided device_type of 'cuda', but CUDA is not available. Disabling
  warnings.warn(
  4%|██▋                                                                 | 1/25 [00:07<02:58,  7.44s/it]
2024-12-18 22:08:54.481 | ERROR    | hyvideo.inference:predict:391 - Generation failed: Input type (float) and bias type (c10::Half) should be the same
2024-12-18 22:08:54.481 | ERROR    | __main__:main:218 - Error occurred: Input type (float) and bias type (c10::Half) should be the same
Traceback (most recent call last):
  File "/Users/keylin/hunyuanvideo/HunyuanVideo_MLX/sample_video_mps.py", line 226, in <module>
    main()
  File "/Users/keylin/hunyuanvideo/HunyuanVideo_MLX/sample_video_mps.py", line 219, in main
    raise e
  File "/Users/keylin/hunyuanvideo/HunyuanVideo_MLX/sample_video_mps.py", line 192, in main
    outputs = hunyuan_video_sampler.predict(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/keylin/hunyuanvideo/HunyuanVideo_MLX/hyvideo/inference.py", line 362, in predict
    samples = self.pipeline(
              ^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/keylin/hunyuanvideo/HunyuanVideo_MLX/hyvideo/diffusion/pipelines/pipeline_hunyuan_video.py", line 991, in __call__
    noise_pred = self.transformer(  # For an input image (129, 192, 336) (1, 256, 256)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/keylin/hunyuanvideo/HunyuanVideo_MLX/hyvideo/modules/models.py", line 634, in forward
    img = self.img_in(img)
          ^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/keylin/hunyuanvideo/HunyuanVideo_MLX/hyvideo/modules/embed_layers.py", line 55, in forward
    x = self.proj(x)
        ^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/site-packages/torch/nn/modules/conv.py", line 725, in forward
    return self._conv_forward(input, self.weight, self.bias)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/site-packages/torch/nn/modules/conv.py", line 720, in _conv_forward
    return F.conv3d(
           ^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/site-packages/torch/utils/_device.py", line 106, in __torch_function__
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
RuntimeError: Input type (float) and bias type (c10::Half) should be the same

**Comment by bemong1** [comment]
I am also experiencing the same issue.
I am running the project on an M4 Pro with 64GB RAM (macOS 15.2).

**Comment by gregcmartin** [comment]
try doing a fresh pull and let me know if you can reproduce, made a lot of changes recently

**Comment by bemong1** [comment]
> try doing a fresh pull and let me know if you can reproduce, made a lot of changes recently

I have pulled the latest version and tested it.
Now, the same issue as #7 is occurring:

ModuleNotFoundError: No module named 'hyvideo.vae.mlx_vae'

**Comment by Keylin2935** [comment]
> try doing a fresh pull and let me know if you can reproduce, made a lot of changes recently

First, thank you for your work and time, really appreciate :)
I remove everything and did a rollback from python 3.12 to 3.11.6.
Unfortunately I do have also the following error now : 
- ModuleNotFoundError: No module named 'hyvideo.vae.mlx_vae

Please find below my stack
All models downloaded successfully!
(venv) (base) keylin@MacBook-Pro-de-keylin HunyuanVideo_MLX % python sample_video_mps.py \      
    --mmgp-mode \
    --mmgp-config configs/mmgp_mlx.json \
    --video-size 544 960 \
    --prompt "A cat walks on the grass, realistic style." \
    --video-length 1 \
    --precision fp16 \
    --vae-precision fp16 \
    --text-encoder-precision fp16 \
    --text-encoder-precision-2 fp16
Traceback (most recent call last):
  File "/Users/keylin/hunyuanvideo/HunyuanVideo_MLX/sample_video_mps.py", line 11, in <module>
    from hyvideo.inference import HunyuanVideo
  File "/Users/keylin/hunyuanvideo/HunyuanVideo_MLX/hyvideo/inference.py", line 19, in <module>
    from hyvideo.diffusion.schedulers import FlowMatchDiscreteScheduler
  File "/Users/keylin/hunyuanvideo/HunyuanVideo_MLX/hyvideo/diffusion/__init__.py", line 1, in <module>
    from .pipelines import HunyuanVideoPipeline
  File "/Users/keylin/hunyuanvideo/HunyuanVideo_MLX/hyvideo/diffusion/pipelines/__init__.py", line 1, in <module>
    from .pipeline_hunyuan_video import HunyuanVideoPipeline
  File "/Users/keylin/hunyuanvideo/HunyuanVideo_MLX/hyvideo/diffusion/pipelines/pipeline_hunyuan_video.py", line 9, in <module>
    from hyvideo.vae.mlx_vae import MLXVAE
ModuleNotFoundError: No module named 'hyvideo.vae.mlx_vae'
(venv) (base) keylin@MacBook-Pro-de-keylin HunyuanVideo_MLX %

**Comment by gregcmartin** [comment]
i had a bug in my gitignore this should be fixed now
