### ISSUE TITLE
hyvideo.vae.mlx_vae import MLXVAE implies that there should be a file named mlx_vae.py inside the hyvideo/vae directory

### ISSUE THREAD

**Issue by andi-808** [gregcmartin/HunyuanVideo_MLX#7]
Traceback (most recent call last):
  File "/Users/andyb/HunyuanVideo_MLX/sample_video_mps.py", line 11, in <module>
    from hyvideo.inference import HunyuanVideo
  File "/Users/andyb/HunyuanVideo_MLX/hyvideo/inference.py", line 19, in <module>
    from hyvideo.diffusion.schedulers import FlowMatchDiscreteScheduler
  File "/Users/andyb/HunyuanVideo_MLX/hyvideo/diffusion/__init__.py", line 1, in <module>
    from .pipelines import HunyuanVideoPipeline
  File "/Users/andyb/HunyuanVideo_MLX/hyvideo/diffusion/pipelines/__init__.py", line 1, in <module>
    from .pipeline_hunyuan_video import HunyuanVideoPipeline
  File "/Users/andyb/HunyuanVideo_MLX/hyvideo/diffusion/pipelines/pipeline_hunyuan_video.py", line 9, in <module>
    from hyvideo.vae.mlx_vae import MLXVAE
ModuleNotFoundError: No module named 'hyvideo.vae.mlx_vae'

**Comment by gregcmartin** [comment]
make sure you pull the latest codebase and let me know if you can reproduce, made lots of changes recently

**Comment by andi-808** [comment]
I pulled the latest changes. That file it is looking for does not currently exist in this repository. Have you checked everything in?

**Comment by randyoo** [comment]
Same here.

**Comment by cchance27** [comment]
ya same issue, seems like the MLXVAE wasn't committed?

**Comment by gregcmartin** [comment]
yeah was a bug in my .gitignore fixed it just now
